[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = ''

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = ["uses_rllib", "uses_sb3", "uses_julia", "uses_cuda", "slow"]
timeout = 1200

[tool.isort]
profile = "black"
known_first_party = ["effective_horizon"]
known_third_party = ["ray", "torch"]
